model:
    # ===== Tuning =====
    freeze_targets: []
    state_dict_mask: []
    use_value_network: False
    enable_baselines: ['winloss', 'build_order', 'built_unit', 'effect', 'upgrade', 'battle']
    # ===== Value =====
    value:
        winloss:
            name: winloss
            cum_stat_keys: ['unit_build', 'research']
            param:
                name: 'winloss'
                input_dim: 1920 #1664
                activation: 'relu'
                norm_type: 'LN'
                res_dim: 256
                res_num: 16
                atan: True
        build_order:
            name: build_order
            cum_stat_keys: ['unit_build', 'effect', 'research']
            param:
                name: 'build_order'
                input_dim: 2016 #1792
                activation: 'relu'
                norm_type: 'LN'
                res_dim: 256
                res_num: 16
                atan: False
        built_unit:
            name: built_unit
            cum_stat_keys: ['unit_build']
            param:
                name: 'built_unit'
                input_dim: 1824 #1664
                activation: 'relu'
                norm_type: 'LN'
                res_dim: 256
                res_num: 16
                atan: False
        effect:
            name: effect
            cum_stat_keys: ['effect']
            param:
                name: 'effect'
                input_dim: 1824 #1664
                activation: 'relu'
                norm_type: 'LN'
                res_dim: 256
                res_num: 16
                atan: False
        upgrade:
            name: upgrade
            cum_stat_keys: ['research']
            param:
                name: 'upgrade'
                input_dim: 1824 #1664
                activation: 'relu'
                norm_type: 'LN'
                res_dim: 256
                res_num: 16
                atan: False
        battle:
            name: battle
            cum_stat_keys: ['unit_build', 'effect', 'research']
            param:
                name: 'battle'
                input_dim: 2016 #1792
                activation: 'relu'
                norm_type: 'LN'
                res_dim: 256
                res_num: 16
                atan: False
    # ===== Encoder =====
    encoder:
        obs_encoder:
            encoder_names: [scalar_encoder, spatial_encoder, entity_encoder]
            scalar_encoder:
                module:
                    agent_statistics:
                        name: agent_statistics
                        arch: fc
                        output_dim: 64
                        baseline_feature: True
                    race:
                        name: race
                        arch: fc
                        output_dim: 32
                        scalar_context: True
                    enemy_race:
                        name: enemy_race
                        arch: fc
                        output_dim: 32
                        scalar_context: True
                    upgrades:
                        name: upgrades
                        arch: fc
                        output_dim: 128
                        baseline_feature: True
                    enemy_upgrades:
                        name: enemy_upgrades
                        arch: fc
                        output_dim: 128
                    time:
                        name: time
                        arch: identity
                    available_actions:
                        name: available_actions
                        arch: fc
                        output_dim: 64
                        scalar_context: True
                    unit_counts_bow:
                        name: unit_counts_bow
                        arch: fc
                        output_dim: 128
                        baseline_feature: True
                    last_delay:
                        name: last_delay
                        arch: fc
                        output_dim: 64
                    last_queued:
                        name: last_queued
                        arch: fc
                        output_dim: 256
                    last_action_type:
                        name: last_action_type
                        arch: fc
                        output_dim: 128
                    mmr:
                        name: mmr
                        arch: fc
                        output_dim: 64
                    cumulative_stat:
                        name: cumulative_stat
                        arch: multi_fc
                        output_dim: 32  # 32x3
                        scalar_context: True
                    beginning_build_order:
                        name: beginning_build_order
                        arch: transformer
                        output_dim: 32
                        scalar_context: True
                        baseline_feature: True
                    immediate_cumulative_stat:
                        name: immediate_cumulative_stat
                        arch: multi_fc
                        output_dim: 32  # 32x3
                        scalar_context: False
                    immediate_beginning_build_order:
                        name: immediate_beginning_build_order
                        arch: transformer
                        output_dim: 32
                        scalar_context: False
                        baseline_feature: True
                activation: 'relu'
                begin_num: 20  # beginning_build_order_num
                output_dim: 1280  # use_stat(True: 1280, False: 1088)
            spatial_encoder:
                input_dim: 52
                resblock_num: 4
                fc_dim: 256
                project_dim: 32
                downsample_type: 'avgpool'
                down_channels: [64, 128, 128]
                activation: 'relu'
                norm_type: 'none'
                head_type: 'avgpool'
            entity_encoder:
                input_dim: 1340  # refer to alphastar_obs_wrapper
                head_dim: 128
                hidden_dim: 1024
                output_dim: 256
                head_num: 2
                mlp_num: 2
                layer_num: 3
                dropout_ratio: 0
                activation: 'relu'
                ln_type: 'post'
            use_score_cumulative: False
        scatter:
            input_dim: 256  # entity_encoder.output_dim
            output_dim: 32
            scatter_type: 'add'
        core_lstm:
            lstm_type: 'normal'
            input_size: 1792  # spatial_encoder.fc_dim + entity_encoder.output_dim + scalar_encoder.output_dim
            hidden_size: 384
            num_layers: 3
            dropout: 0.0
        score_cumulative:
            input_dim: 13
            output_dim: 64
            activation: 'relu'
    # ===== Policy =====
    policy:
        sl_training: False
        head:
            head_names: [action_type_head, delay_head, queued_head, selected_units_head, target_unit_head, location_head]
            action_type_head:
                input_dim: 384  # core.hidden_size
                res_dim: 256
                res_num: 2
                action_num: 327
                action_map_dim: 256
                gate_dim: 1024
                context_dim: 256
                activation: 'relu'
                norm_type: 'LN'
                ln_type: 'normal'
                use_mask: False
            delay_head:
                input_dim: 1024  # action_type_head.gate_dim
                decode_dim: 256
                delay_dim: 128
                delay_map_dim: 256
                activation: 'relu'
            queued_head:
                input_dim: 1024  # action_type_head.gate_dim
                decode_dim: 256
                queued_dim: 2
                queued_map_dim: 256
                activation: 'relu'
            selected_units_head:
                lstm_type: 'pytorch'
                lstm_norm_type: 'none'
                lstm_dropout: 0.
                input_dim: 1024  # action_type_head.gate_dim
                entity_embedding_dim: 256  # entity_encoder.output_dim
                key_dim: 32
                unit_type_dim: 259
                func_dim: 256
                hidden_dim: 32
                num_layers: 1
                max_entity_num: 64
                activation: 'relu'
                use_mask: False
                units_reorder: False
            target_unit_head:
                input_dim: 1024  # action_type_head.gate_dim
                entity_embedding_dim: 256  # entity_encoder.output_dim
                key_dim: 32
                unit_type_dim: 259
                func_dim: 256
                activation: 'relu'
                use_mask: False
                embedding_norm: True
            location_head:
                input_dim: 1024
                proj_dim: 1024
                upsample_type: 'bilinear'
                upsample_dims: [128, 64, 1]  # len(upsample_dims)-len(down_channels)+1 = ratio
                res_dim: 128
                res_num: 4
                reshape_size: [16, 16]
                reshape_channel: 4  # entity_encoder.gate_dim / reshape_size
                map_skip_dim: 128  # spatial_encoder.down_channels[-1]
                activation: 'prelu'
                output_type: 'cls'  # ['cls', 'soft_argmax']
                use_mask: False
                location_expand_ratio: 1
            #             loc_type: 'alphastar'
