data:
    unroll_len: 4
    batch_size: 3
model:
    use_value_network: True
    encoder:
        obs_encoder:
            use_score_cumulative: True
learner:
    unroll_len: 4
    batch_size: 3
    use_cuda: False
    action_output_types:
        action_type: logit
        delay: logit
        queued: logit
        selected_units: logit
        target_units: logit
        target_location: logit
    kl:
        action_type_kl_seconds: 240
    vtrace:
        min_clip: 0.8
        max_clip: 1.2
    upgo:
        min_clip: 0.8
        max_clip: 1.2
    temperature: 0.8
    loss_weights:
        baseline:
            winloss: 10.0
            build_order: 1.0
            built_unit: 1.0
            effect: 1.0
            upgrade: 1.0
            battle: 0.5
        pg:
            winloss: 1.0
            build_order: 4.0
            built_unit: 6.0
            effect: 6.0
            upgrade: 6.0
            battle: 1.0
        upgo:
            winloss: 1.0
        kl: 0.002
        action_type_kl: 0.1
        entropy: 0.0001
        filter_kl: 0.0
        filter_kl_train: 0.0
        filter_kl_build: 0.0
    gammas:
        baseline:
            winloss: 1.0
            build_order: 1.0
            built_unit: 1.0
            effect: 1.0
            upgrade: 1.0
            battle: 0.997
        pg:
            winloss: 1.0
            build_order: 1.0
            built_unit: 1.0
            effect: 1.0
            upgrade: 1.0
            battle: 0.997
